# Generated by Django 3.1 on 2021-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210809_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='variationfield',
            field=models.BooleanField(default=True),
        ),
    ]
