# Generated by Django 3.1 on 2021-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210809_1510'),
        ('carts', '0002_auto_20210722_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
