# Generated by Django 3.1 on 2021-11-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210911_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_field',
            new_name='date_added',
        ),
    ]
